//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranscriptionComparator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Transcriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Transcriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TranscriptionComparator.Transcriptions", typeof(Transcriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group 4: Langqin
        ///ANIMAL: (20.2) ()
        ///世界动物比较多。 但是世界那个↑动物保护组织的↑标志↑是大熊猫。所以呢↑应该说是中国的大熊猫是比较著名的↑动物吧。因为它成为世界动物的↑那个协会的↑标志哈。(1.2)还有就是↑我们知道的每个国家↑都有这个保护动物。
        ///
        ///LEADER: (21.1) (1xEM juede)
        ///Mm 像中国的传统小说吧举个↑例子像↑三国演义。↑那么↑像刘备他没有↑武功对吧。↑他也没有那个什么力气。但是呢他却↑领导力了关张领导了千军万马。那么我↑觉得(EM)只有一点↑就是他－他能↑知道就是认人↑善用。
        ///
        ///SCHOOL: (27.3) (1xDMF juede, 1xDMM renwei)
        ///Mm 这个↑可能得分专业↑那么从我－↑我↑比如文科专业啊。理科我不↑了解那么我觉得(DM)是↑英语。 因为↑这个东西↑对我们来说它是完全是一个↑不同的思维方式。就是说它超越了你的经验。↑那么跟↑教学方法也有关系。因为↑我们一直没有遇到↑很好的。↑迄今为止我认为(DM)没有很好的英语老师。那么↑他死活的教你我们也学↑不会。
        ///
        ///SECOND LANG: (19.3 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ch_Interrating_Kang {
            get {
                return ResourceManager.GetString("ch_Interrating_Kang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group 4: Langqin
        ///ANIMAL: (20.2) ()
        ///Oh 世界动物比较多。但是世界呢个动物保护主旨的标志是大熊猫。所以呢应该说是中国的大熊猫是比较著名的动物吧。因为它成为 世界动物的那个协会的标志哈。(1.2)嗯还有就是我们知道的每个国家↑都有这个(1.0)保护动物。
        ///
        ///LEADER: (21.1) (1xEM juede)
        ///Mm：像 ↑中国的成功小说吧举个↑例子向三国演义。那么：像 刘备他没用武功对吧。他也没有那个什么↑力气。但是呢他却领导了关张领导了千军万马。那么我↑觉得(EM)只有一点就是他－他能够↑知道就是认人善用。
        ///
        ///SCHOOL: (27.3) (1xDMF juede， 1xDMM renwei)
        ///Mm 这个可能得跟↑专业那么从我－我边文科专业立刻。理科我不↑了解那么我觉得(DM)是↑英语。因为这个东西对我们来说它是完全是一个不同的思维方式。就说它超越了你的经验。那么：(1.0)跟叫教学方法有关系。因为我们一直没有遇到↑很好的。迄今我认为(DM)没有很好的英语老师。那么：他死活的教你我们也学不会。
        ///
        ///SECOND LANG: (19.2) ()
        ///嗯第二种语 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ch_Interrating_Lucy {
            get {
                return ResourceManager.GetString("ch_Interrating_Lucy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group 1: Kath
        ///ANIMAL: (35.7)
        ///The bravest (.) animal (.8) that’s actually a pretty hard ↑question. (.4) Um: (.4) I ↑guess (EM) the bravest animal would probably be: (1.2) something that (.) lives in the ↑ocean because (DIR) the ocean is a very scary place. (.5) Um: (.9) especially: because there are (.5) a lot of things that live deep under the water that will kill you ((laughs)). (1.1) Um so I ↑guess (EM) being like (1.3) a fish or: a dolphin (.3) would be very brave (.2) because you don’t know what’s bel [rest of string was truncated]&quot;;.
        /// </summary>
        public static string en_Interrating_Lucy {
            get {
                return ResourceManager.GetString("en_Interrating_Lucy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group 1: Kath
        ///Animal: (35.7)
        ///The ↑bravest animal um:  that’s actually a pretty hard ↑question. Um: I guess the bravest animal would probably be: (1.3) something that lives in the ↑ocean because the ocean is a very scary place um: (1.0) especially because there are a lot of things that live deep in the ↑water that will kill you [laughs] um so I guess being like a fish or a dolphin would be very ↑brave because you don’t know what’s below you and it could just come up and eat you.
        ///
        ///Leader: (32.6)
        ///Um a goo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string en_Interrating_William {
            get {
                return ResourceManager.GetString("en_Interrating_William", resourceCulture);
            }
        }
    }
}
